format_version: v1.0
type: UniqueComponent
attributes: {id: lib_wolfcrypt}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: cryptoCrya_03710}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'false'}
  - type: Boolean
    attributes: {id: cryptoCrya_U2803}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'false'}
  - type: Boolean
    attributes: {id: cryptoCrya_U2805}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'false'}
  - type: Combo
    attributes: {id: wolfSslRTOSSupport}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: FreeRTOS}
  - type: Boolean
    attributes: {id: wolfcrypt_aes_cbc_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_aes_ctr_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_aes_ecb_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_aes_gcm_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_aes_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_ecc_hw}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_hashdrng}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_havezlib}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_hkdf}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_hmac}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_hw}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_random}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_random_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_randomtest}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_rsa_hw}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_sha1_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_sha224}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_sha264_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_sha384}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_sha512}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_supportcompression}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: LIB_WOLFCRYPT_ZLIB_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: lib_zlib}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: lib_zlib}
- type: ElementPosition
  attributes: {x: '197', y: '312', id: lib_wolfcrypt}
