format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Setting
    attributes: {id: FREERTOS_IAR_INCLUDE_DIRS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: FREERTOS_IAR_SAM_PORT_ASM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: FREERTOS_IAR_SAM_PORT_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: FREERTOS_IAR_SAM_PORT_MACRO_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: FREERTOS_IAR_SAM_PORT_TICK_CONFIG_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: FREERTOS_TOTAL_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '102400'}
  - type: Setting
    attributes: {id: FREERTOS_XC32CPP_INCLUDE_DIRS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Setting
    attributes: {id: FREERTOS_XC32_INCLUDE_DIRS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: FREERTOS_XC32_SAM_PORT_ASM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: FREERTOS_XC32_SAM_PORT_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: FREERTOS_XC32_SAM_PORT_MACRO_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: FREERTOS_XC32_SAM_PORT_TICK_CONFIG_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '342', y: '144', id: FreeRTOS}
